server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://cloudcottage.cn:3308/hummingSql?useSSL=true&useUnicode=true&serverTimezone=Hongkong&characterEncoding=utf-8&autoReconnect=true
    username : root
    password : 147258369
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 906861749@qq.com #发送邮件的邮箱地址
    password:  ycsrfmicaafgbaib    #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 906861749@qq.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
